"""
Forbidden Zone Trespassing Detection System  v13.0
Powered by YOLOv8 + OpenCV  |  Live Async Pipeline
Master Degree Project - Cybersecurity

ARCHITECTURE v6.0 — Single-pass live display:

  THREAD 1 (Producer — background)
    Read frame -> YOLOv8 every N frames -> Kalman prediction every frame
    -> annotate frame -> push to display queue

  THREAD 2 (Consumer — main thread)
    Pop from queue -> imshow at exactly native FPS
    -> user sees smooth video, zero judder

  No intermediate files. No two-pass waiting.
  Zone is drawn once at startup, then live analysis begins immediately.

  Kalman filter (constant-velocity model, same as SORT/DeepSORT):
    - Runs on EVERY frame (not just detection frames)
    - Predicts box position between YOLO detections
    - Result: boxes move smoothly even when YOLO runs every 3rd frame

  v7.0 NEW FEATURES (added, nothing removed):
  - Dual zones: YELLOW (warning) + RED (violation) drawn at startup
  - Heatmap: accumulates foot positions, saved as PNG after analysis
  - HTML report: interactive charts, stats, heatmap, timeline

  v11.0 NEW FEATURES:
  - Temporal Pattern Analysis: violation frequency per time segment
  - Person Re-identification: color histogram signature matching

  v12.0 FIXES:
  - Multi-point zone detection (6 points) — no more missed detections
  - RE-ID badge removed from video (logic kept, results in HTML report)
"""

import cv2
import numpy as np
import sys
import os
import csv
import json
import time
import math
import threading
import queue
from datetime import datetime, timedelta
from collections import defaultdict

try:
    import tkinter as tk
    from tkinter import filedialog
    HAS_TK = True
except ImportError:
    HAS_TK = False

try:
    from ultralytics import YOLO
except ImportError:
    print("[ERROR] Run: pip install ultralytics")
    sys.exit(1)

# Email notification (optional — only if email_config.py exists)
try:
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text      import MIMEText
    from email.mime.image     import MIMEImage
    HAS_EMAIL = True
except ImportError:
    HAS_EMAIL = False

def _load_email_config():
    """Load email credentials from email_config.py if it exists."""
    try:
        import importlib.util, os
        cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "email_config.py")
        if not os.path.isfile(cfg_path):
            return None
        spec   = importlib.util.spec_from_file_location("email_config", cfg_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return {
            "sender":   getattr(module, "EMAIL_SENDER",   None),
            "password": getattr(module, "EMAIL_PASSWORD", None),
            "receiver": getattr(module, "EMAIL_RECEIVER", None),
        }
    except Exception as e:
        print(f"[WARN] Could not load email_config.py: {e}")
        return None

def send_violation_email(cfg, screenshot_bgr, frame_idx, fps,
                         n_violators, risk_info=""):
    """
    Send an email alert with the violation screenshot attached.
    Called in a daemon thread so it never blocks the display loop.
    """
    if not HAS_EMAIL or cfg is None:
        return
    if not all([cfg.get("sender"), cfg.get("password"), cfg.get("receiver")]):
        print("[WARN] Incomplete email config — skipping notification.")
        return

    def _send():
        try:
            elapsed = str(timedelta(seconds=int(frame_idx / fps))) if fps > 0 else "N/A"
            subject = f"[ALERT] Forbidden Zone Violation — {elapsed}"
            body    = f"""
<html><body style="font-family:Arial,sans-serif;background:#0f1117;color:#e0e0e0;padding:24px;">
<h2 style="color:#e53935;">&#128274; FORBIDDEN ZONE VIOLATION DETECTED</h2>
<table style="border-collapse:collapse;width:100%;max-width:500px;">
  <tr><td style="padding:8px;color:#888;">Time in video</td>
      <td style="padding:8px;color:#fff;font-weight:bold;">{elapsed}</td></tr>
  <tr><td style="padding:8px;color:#888;">Frame</td>
      <td style="padding:8px;color:#fff;">{frame_idx}</td></tr>
  <tr><td style="padding:8px;color:#888;">Violators in zone</td>
      <td style="padding:8px;color:#e53935;font-weight:bold;">{n_violators}</td></tr>
  {'<tr><td style="padding:8px;color:#888;">Risk info</td><td style="padding:8px;color:#ffd600;">' + risk_info + '</td></tr>' if risk_info else ''}
</table>
<p style="margin-top:16px;color:#666;font-size:0.85rem;">
  Screenshot attached. Generated by Forbidden Zone Detection System v7.0
</p>
</body></html>"""

            msg = MIMEMultipart("related")
            msg["Subject"] = subject
            msg["From"]    = cfg["sender"]
            msg["To"]      = cfg["receiver"]
            msg.attach(MIMEText(body, "html"))

            # Encode screenshot as JPEG and attach
            ret, buf = cv2.imencode(".jpg", screenshot_bgr,
                                    [cv2.IMWRITE_JPEG_QUALITY, 85])
            if ret:
                img_attachment = MIMEImage(buf.tobytes(), _subtype="jpeg")
                img_attachment.add_header("Content-Disposition", "attachment",
                                          filename=f"violation_frame_{frame_idx}.jpg")
                msg.attach(img_attachment)

            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(cfg["sender"], cfg["password"])
                server.sendmail(cfg["sender"], cfg["receiver"], msg.as_string())
            print(f"[INFO] Violation email sent (frame {frame_idx})")

        except Exception as e:
            print(f"[WARN] Email failed: {e}")

    # Run in background thread — never blocks display
    threading.Thread(target=_send, daemon=True).start()

# ─────────────────────────────────────────────────────────────────────────────
#  TUNABLE CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────
DETECT_EVERY  = 3     # run YOLO every N frames; Kalman fills the rest
DETECT_SCALE  = 0.5   # scale for YOLO inference
DISPLAY_SCALE = 0.5   # scale for display window (same = no extra resize)
QUEUE_SIZE    = 64    # frame buffer between producer and display

FONT_MAIN  = cv2.FONT_HERSHEY_DUPLEX
FONT_SMALL = cv2.FONT_HERSHEY_SIMPLEX

# ─────────────────────────────────────────────────────────────────────────────
#  RELATIVE UI SIZING
# ─────────────────────────────────────────────────────────────────────────────
def ui(fw, fh):
    """
    Fully dynamic UI sizing.
    Uses the DIAGONAL of the frame as the base metric — this gives
    balanced sizing for both portrait and landscape orientations.
    A 1920x1080 landscape and a 1080x1920 portrait both have the same
    diagonal (~2203px) so text/lines look identical on both.
    """
    diag = math.hypot(fw, fh)          # diagonal in pixels
    # Reference diagonal for a 1280x720 frame ≈ 1469px
    # All constants are tuned for that reference and scale linearly.
    REF  = 1469.0
    s    = diag / REF                  # scale factor

    # Font sizes — clamp so they never go below readable minimum
    fs_large  = max(0.45, 0.65 * s)
    fs_medium = max(0.38, 0.52 * s)
    fs_small  = max(0.30, 0.40 * s)

    # Line widths
    lw_thick = max(1, int(2.0 * s))
    lw_thin  = max(1, int(1.2 * s))

    # UI element heights — scale with diagonal
    hud_h   = max(40,  int(52  * s))
    alert_h = max(28,  int(36  * s))
    pad     = max(5,   int(8   * s))
    dot_r   = max(4,   int(6   * s))

    return {
        "md":         min(fw, fh),
        "diag":       diag,
        "s":          s,
        "fs_large":   fs_large,
        "fs_medium":  fs_medium,
        "fs_small":   fs_small,
        "lw_thick":   lw_thick,
        "lw_thin":    lw_thin,
        "hud_h":      hud_h,
        "alert_h":    alert_h,
        "pad":        pad,
        "dot_r":      dot_r,
        "zone_alpha": 0.30,
    }

# ─────────────────────────────────────────────────────────────────────────────
#  COLOURS (BGR)
# ─────────────────────────────────────────────────────────────────────────────
C_RED        = (0,   30,  220)
C_DARK_RED   = (0,   0,   140)
C_ORANGE     = (0,   140, 255)
C_GREEN      = (50,  200,  50)
C_WHITE      = (255, 255, 255)
C_LIGHT_GRAY = (210, 210, 210)
C_PANEL_BG   = (18,  18,   24)
C_ZONE_FILL  = (0,   30,  180)
C_YELLOW     = (0,   210, 255)   # BGR yellow
C_YELLOW_FILL= (0,   180, 220)

# ─────────────────────────────────────────────────────────────────────────────
#  FILE PICKERS
# ─────────────────────────────────────────────────────────────────────────────
def pick_video_file():
    if HAS_TK:
        root = tk.Tk(); root.withdraw(); root.attributes("-topmost", True)
        path = filedialog.askopenfilename(
            title="Select input video",
            filetypes=[("Video files", "*.mp4 *.avi *.mov *.mkv *.wmv *.flv *.webm"),
                       ("All files", "*.*")])
        root.destroy()
        if path:
            return path
    print("\n[FILE PICKER] Enter full path to video file:")
    return input("  > ").strip().strip('"').strip("'")

def pick_output_file(default):
    if HAS_TK:
        root = tk.Tk(); root.withdraw(); root.attributes("-topmost", True)
        path = filedialog.asksaveasfilename(
            title="Save output video as (optional — press Cancel to skip)",
            initialfile=os.path.basename(default),
            defaultextension=".mp4",
            filetypes=[("MP4 video", "*.mp4"), ("All files", "*.*")])
        root.destroy()
        if path:
            return path
    return None   # user cancelled = no save

# ─────────────────────────────────────────────────────────────────────────────
#  WINDOW HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def _fit_window(win_name, fw, fh):
    max_w, max_h = 1600, 900
    scale = min(max_w / fw, max_h / fh, 1.0)
    cv2.resizeWindow(win_name, max(1, int(fw * scale)), max(1, int(fh * scale)))

# ─────────────────────────────────────────────────────────────────────────────
#  KALMAN BOX TRACKER  (constant-velocity, same model as SORT/DeepSORT)
#  State:       [cx, cy, w, h, vx, vy, vw, vh]
#  Measurement: [cx, cy, w, h]
# ─────────────────────────────────────────────────────────────────────────────
class KalmanBoxTracker:
    count = 0

    def __init__(self, box):
        self.id       = KalmanBoxTracker.count
        KalmanBoxTracker.count += 1
        self.hits     = 1
        self.no_match = 0

        self.kf_x = np.zeros((8, 1), dtype=np.float32)
        cx = box[0] + box[2] / 2
        cy = box[1] + box[3] / 2
        self.kf_x[:4, 0] = [cx, cy, float(box[2]), float(box[3])]

        self.kf_F = np.eye(8, dtype=np.float32)
        for i in range(4):
            self.kf_F[i, i + 4] = 1.0

        self.kf_H = np.zeros((4, 8), dtype=np.float32)
        for i in range(4):
            self.kf_H[i, i] = 1.0

        self.kf_P = np.eye(8, dtype=np.float32) * 10.0
        self.kf_P[4:, 4:] *= 1000.0
        self.kf_Q = np.eye(8, dtype=np.float32)
        self.kf_Q[4:, 4:] *= 0.01
        self.kf_R = np.eye(4, dtype=np.float32) * 1.0

    def predict(self):
        self.kf_x = self.kf_F @ self.kf_x
        self.kf_P = self.kf_F @ self.kf_P @ self.kf_F.T + self.kf_Q
        return self._to_box()

    def update(self, box):
        cx = box[0] + box[2] / 2
        cy = box[1] + box[3] / 2
        z  = np.array([[cx], [cy], [float(box[2])], [float(box[3])]], dtype=np.float32)
        S  = self.kf_H @ self.kf_P @ self.kf_H.T + self.kf_R
        K  = self.kf_P @ self.kf_H.T @ np.linalg.inv(S)
        self.kf_x  = self.kf_x + K @ (z - self.kf_H @ self.kf_x)
        self.kf_P  = (np.eye(8, dtype=np.float32) - K @ self.kf_H) @ self.kf_P
        self.hits     += 1
        self.no_match  = 0

    def _to_box(self):
        cx, cy, w, h = self.kf_x[:4, 0]
        return (int(cx - w / 2), int(cy - h / 2), int(w), int(h))

    def get_box(self):
        return self._to_box()

# ─────────────────────────────────────────────────────────────────────────────
#  CENTROID TRACKER
# ─────────────────────────────────────────────────────────────────────────────
class CentroidTracker:
    def __init__(self, max_disappeared=1, max_distance=80):
        self.next_id     = 0
        self.objects     = {}
        self.boxes       = {}
        self.disappeared = defaultdict(int)
        self.max_dis     = max_disappeared
        self.max_dist    = max_distance

    def _c(self, b):
        return (int(b[0] + b[2] / 2), int(b[1] + b[3] / 2))

    def update(self, boxes):
        if not boxes:
            for oid in list(self.disappeared):
                self.disappeared[oid] += 1
                if self.disappeared[oid] > self.max_dis:
                    del self.objects[oid]
                    del self.boxes[oid]
                    del self.disappeared[oid]
            return dict(self.objects), dict(self.boxes)

        nc = [self._c(b) for b in boxes]
        if not self.objects:
            for c, b in zip(nc, boxes):
                self.objects[self.next_id] = c
                self.boxes[self.next_id]   = b
                self.disappeared[self.next_id] = 0
                self.next_id += 1
        else:
            ids = list(self.objects.keys())
            oc  = list(self.objects.values())
            D   = np.array([[math.hypot(a[0]-b[0], a[1]-b[1])
                             for b in nc] for a in oc])
            rows = D.min(axis=1).argsort()
            cols = D.argmin(axis=1)[rows]
            ur, uc = set(), set()
            for r, c in zip(rows, cols):
                if r in ur or c in uc or D[r, c] > self.max_dist:
                    continue
                oid = ids[r]
                self.objects[oid] = nc[c]
                self.boxes[oid]   = boxes[c]
                self.disappeared[oid] = 0
                ur.add(r); uc.add(c)
            for r in set(range(len(ids))) - ur:
                oid = ids[r]
                self.disappeared[oid] += 1
                if self.disappeared[oid] > self.max_dis:
                    del self.objects[oid]
                    del self.boxes[oid]
                    del self.disappeared[oid]
            for c in set(range(len(nc))) - uc:
                self.objects[self.next_id] = nc[c]
                self.boxes[self.next_id]   = boxes[c]
                self.disappeared[self.next_id] = 0
                self.next_id += 1
        return dict(self.objects), dict(self.boxes)

# ─────────────────────────────────────────────────────────────────────────────
#  ZONE HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def auto_zone(w, h, n=1):
    if n == 1:
        return [[(0, int(h*.35)), (w, int(h*.35)),
                 (w, int(h*.75)), (0, int(h*.75))]]
    y0a, y1a = int(h*.28), int(h*.50)
    y0b, y1b = int(h*.52), int(h*.74)
    return [[(0,y0a),(w,y0a),(w,y1a),(0,y1a)],
            [(0,y0b),(w,y0b),(w,y1b),(0,y1b)]]

def build_mask(h, w, poly):
    m = np.zeros((h, w), dtype=np.uint8)
    cv2.fillPoly(m, [np.array(poly, dtype=np.int32)], 255)
    return m

def feet_in_zone(box, mask):
    """
    Multi-point zone check — tests 5 points across the lower half of the
    bounding box. If ANY point is inside the zone mask the person counts
    as being in the zone. This prevents misses when a large foreground
    person's centre-bottom falls just outside the zone boundary.

    Points tested:
      - bottom-centre  (feet)
      - bottom-left    (25% from left)
      - bottom-right   (75% from left)
      - mid-centre     (at 75% height)
      - mid-left/right (at 75% height, 25% and 75% width)
    """
    x, y, w, h = box
    mh, mw = mask.shape[:2]

    def _in(px, py):
        px = min(max(int(px), 0), mw - 1)
        py = min(max(int(py), 0), mh - 1)
        return mask[py, px] > 0

    # Bottom row (feet level)
    if _in(x + w * 0.50, y + h):        return True  # centre-bottom
    if _in(x + w * 0.25, y + h):        return True  # left-bottom
    if _in(x + w * 0.75, y + h):        return True  # right-bottom
    # Mid-lower body (75% height)
    if _in(x + w * 0.50, y + h * 0.75): return True  # centre-mid
    if _in(x + w * 0.25, y + h * 0.75): return True  # left-mid
    if _in(x + w * 0.75, y + h * 0.75): return True  # right-mid
    return False


# ─────────────────────────────────────────────────────────────────────────────
#  HEATMAP ACCUMULATOR
# ─────────────────────────────────────────────────────────────────────────────
class Heatmap:
    """Accumulates foot-point positions and renders a colourmap overlay."""
    def __init__(self, h, w):
        self.acc = np.zeros((h, w), dtype=np.float32)
        self.h   = h
        self.w   = w

    def add(self, boxes):
        """Add foot centre of each box to the accumulator."""
        for x, y, bw, bh in boxes:
            cx = min(max(int(x + bw / 2), 0), self.w - 1)
            cy = min(max(int(y + bh),     0), self.h - 1)
            # Gaussian splat around foot point
            r = max(self.h, self.w) // 40
            x0, x1 = max(0, cx-r), min(self.w, cx+r)
            y0, y1 = max(0, cy-r), min(self.h, cy+r)
            for iy in range(y0, y1):
                for ix in range(x0, x1):
                    d = math.hypot(ix-cx, iy-cy)
                    if d < r:
                        self.acc[iy, ix] += 1.0 - d/r

    def render(self, base_frame):
        """Return base_frame with heatmap blended on top."""
        if self.acc.max() == 0:
            return base_frame.copy()
        norm = (self.acc / self.acc.max() * 255).astype(np.uint8)
        coloured = cv2.applyColorMap(norm, cv2.COLORMAP_JET)
        mask     = (norm > 10).astype(np.uint8)[:, :, np.newaxis]
        blended  = base_frame.copy()
        blended  = np.where(mask, cv2.addWeighted(base_frame, 0.4, coloured, 0.6, 0), base_frame)
        return blended.astype(np.uint8)

    def save_png(self, path, base_frame):
        img = self.render(base_frame)
        cv2.imwrite(path, img)
        print(f"[INFO] Heatmap saved: {path}")


# ─────────────────────────────────────────────────────────────────────────────
#  HTML REPORT GENERATOR
# ─────────────────────────────────────────────────────────────────────────────
def generate_html_report(report_path, heatmap_png_path, stats):
    """
    stats dict keys:
      video_name, duration_s, fps, total_frames,
      total_people, total_yellow, total_red,
      yellow_timeline: [(time_s, count), ...],
      red_timeline:    [(time_s, count), ...],
      peak_yellow_time, peak_red_time,
      peak_yellow_count, peak_red_count,
      generated_at
    """
    import base64, os

    # Embed heatmap as base64 so the HTML is self-contained
    heatmap_b64 = ""
    if heatmap_png_path and os.path.isfile(heatmap_png_path):
        with open(heatmap_png_path, "rb") as f:
            heatmap_b64 = base64.b64encode(f.read()).decode()

    import json as _json, base64 as _b64
    traj_json = _json.dumps(stats.get("trajectories", {}))
    frame_w   = stats.get("frame_w", 640)
    frame_h   = stats.get("frame_h", 360)

    # Encode first frame as base64 JPEG for trajectory background
    first_frame_b64 = ""
    first_frame_img = stats.get("first_frame_img")
    if first_frame_img is not None:
        try:
            ret, buf = cv2.imencode(".jpg", first_frame_img,
                                    [cv2.IMWRITE_JPEG_QUALITY, 70])
            if ret:
                first_frame_b64 = _b64.b64encode(buf.tobytes()).decode()
        except Exception:
            pass

    # Build timeline data for Chart.js
    def tl_to_js(tl):
        labels = [f"{t:.1f}" for t, _ in tl]
        values = [c for _, c in tl]
        return str(labels), str(values)

    yl, yv = tl_to_js(stats.get("yellow_timeline", []))
    rl, rv = tl_to_js(stats.get("red_timeline", []))

    # Temporal segments
    segments   = stats.get("temporal_segments", [])
    temp_labels  = str([s["label"] for s in segments])
    temp_red     = str([s["red_count"] for s in segments])
    temp_yellow  = str([s["yellow_count"] for s in segments])
    peak_indices = [i for i, s in enumerate(segments) if s.get("peak")]
    temp_peak    = str(peak_indices[0] if peak_indices else -1)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Forbidden Zone Detection Report</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: #0f1117; color: #e0e0e0; }}
  header {{ background: linear-gradient(135deg, #1a1a2e, #16213e);
            padding: 32px 40px; border-bottom: 2px solid #e53935; }}
  header h1 {{ font-size: 1.8rem; color: #fff; letter-spacing: 2px; }}
  header p  {{ color: #888; margin-top: 6px; font-size: 0.9rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px,1fr));
           gap: 16px; padding: 32px 40px 0; }}
  .card {{ background: #1e1e2e; border-radius: 12px; padding: 20px;
           border-left: 4px solid #e53935; }}
  .card.yellow {{ border-left-color: #ffd600; }}
  .card.green  {{ border-left-color: #43a047; }}
  .card.blue   {{ border-left-color: #1e88e5; }}
  .card h3 {{ font-size: 0.75rem; color: #888; text-transform: uppercase;
              letter-spacing: 1px; margin-bottom: 8px; }}
  .card .value {{ font-size: 2rem; font-weight: 700; color: #fff; }}
  .card .sub   {{ font-size: 0.8rem; color: #666; margin-top: 4px; }}
  .section {{ padding: 32px 40px; }}
  .section h2 {{ font-size: 1.1rem; color: #e53935; text-transform: uppercase;
                 letter-spacing: 2px; margin-bottom: 20px;
                 border-bottom: 1px solid #333; padding-bottom: 8px; }}
  .chart-wrap {{ background: #1e1e2e; border-radius: 12px; padding: 24px;
                 margin-bottom: 24px; }}
  .heatmap-img {{ max-width: 100%; border-radius: 12px;
                  border: 1px solid #333; display: block; margin: 0 auto; }}
  .two-col {{ display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }}
  footer {{ text-align: center; padding: 24px; color: #444; font-size: 0.8rem; }}
  @media(max-width:700px) {{ .two-col {{ grid-template-columns: 1fr; }} }}
</style>
</head>
<body>

<header>
  <h1>&#128274; Forbidden Zone Detection Report</h1>
  <p>{stats.get('video_name','Unknown')} &nbsp;|&nbsp;
     Generated: {stats.get('generated_at','')} &nbsp;|&nbsp;
     Duration: {stats.get('duration_s',0):.1f}s &nbsp;|&nbsp;
     {stats.get('fps',0):.1f} FPS &nbsp;|&nbsp;
     {stats.get('total_frames',0)} frames</p>
</header>

<div class="grid">
  <div class="card blue">
    <h3>Total People Detected</h3>
    <div class="value">{stats.get('total_people',0)}</div>
    <div class="sub">unique tracks</div>
  </div>
  <div class="card yellow">
    <h3>Warning Zone Events</h3>
    <div class="value">{stats.get('total_yellow',0)}</div>
    <div class="sub">peak: {stats.get('peak_yellow_count',0)} @ {stats.get('peak_yellow_time',0):.1f}s</div>
  </div>
  <div class="card">
    <h3>Violation Zone Events</h3>
    <div class="value">{stats.get('total_red',0)}</div>
    <div class="sub">peak: {stats.get('peak_red_count',0)} @ {stats.get('peak_red_time',0):.1f}s</div>
  </div>
  <div class="card green">
    <h3>Safe Passages</h3>
    <div class="value">{max(0, stats.get('total_people',0) - stats.get('total_red',0))}</div>
    <div class="sub">no violation detected</div>
  </div>
  <div class="card blue">
    <h3>Re-identified Persons</h3>
    <div class="value">{stats.get('reid_unique',0)}</div>
    <div class="sub">{stats.get('reid_returns',0)} return(s) detected</div>
  </div>
</div>

<div class="section">
  <h2>Activity Timeline</h2>
  <div class="two-col">
    <div class="chart-wrap">
      <canvas id="yellowChart"></canvas>
    </div>
    <div class="chart-wrap">
      <canvas id="redChart"></canvas>
    </div>
  </div>
  <div class="chart-wrap">
    <canvas id="combinedChart"></canvas>
  </div>
</div>

<div class="section">
  <h2>Violation Frequency by Time Segment</h2>
  <div class="chart-wrap">
    <canvas id="temporalChart"></canvas>
  </div>
</div>

<div class="section">
  <h2>Movement Trajectories</h2>
  <p style="color:#666;font-size:0.85rem;margin-bottom:12px;">
    Each line shows the path of a tracked person.
    Green = safe &nbsp;|&nbsp; Yellow = warning zone &nbsp;|&nbsp; Red = violation zone
  </p>
  <div class="chart-wrap" style="position:relative;">
    <canvas id="trajCanvas" style="width:100%;background:#111;border-radius:8px;"></canvas>
  </div>
</div>

{'<div class="section"><h2>Movement Heatmap</h2><img class="heatmap-img" src="data:image/png;base64,' + heatmap_b64 + '" alt="Heatmap"/></div>' if heatmap_b64 else ''}

<footer>Forbidden Zone Detection System v7.0 &nbsp;|&nbsp; Master Degree Project &nbsp;|&nbsp; Cybersecurity</footer>

<script>
const ylabels   = {yl};
const yvalues   = {yv};
const rlabels   = {rl};
const rvalues   = {rv};

const chartOpts = (label, color, labels, data) => ({{
  type: 'line',
  data: {{
    labels,
    datasets: [{{ label, data, borderColor: color, backgroundColor: color+'33',
                  fill: true, tension: 0.4, pointRadius: 0, borderWidth: 2 }}]
  }},
  options: {{
    responsive: true,
    plugins: {{ legend: {{ labels: {{ color: '#ccc' }} }} }},
    scales: {{
      x: {{ ticks: {{ color:'#666', maxTicksLimit:10 }}, grid: {{ color:'#222' }},
            title: {{ display:true, text:'Time (s)', color:'#666' }} }},
      y: {{ ticks: {{ color:'#666' }}, grid: {{ color:'#222' }}, beginAtZero:true,
            title: {{ display:true, text:'Persons', color:'#666' }} }}
    }}
  }}
}});

new Chart(document.getElementById('yellowChart'),
  chartOpts('Warning Zone (Yellow)', '#ffd600', ylabels, yvalues));
new Chart(document.getElementById('redChart'),
  chartOpts('Violation Zone (Red)', '#e53935', rlabels, rvalues));

// Combined

// Temporal pattern chart
const tempSegs  = {temp_labels};
const tempRed   = {temp_red};
const tempYellow= {temp_yellow};
const peakIdx   = {temp_peak};

new Chart(document.getElementById('temporalChart'), {{
  type: 'bar',
  data: {{
    labels: tempSegs,
    datasets: [
      {{ label:'Red Violations', data:tempRed,
         backgroundColor: tempRed.map((v,i) =>
           i===peakIdx ? '#ff1744' : '#e5393588'),
         borderColor:'#e53935', borderWidth:1 }},
      {{ label:'Yellow Warnings', data:tempYellow,
         backgroundColor:'#ffd60044',
         borderColor:'#ffd600', borderWidth:1 }}
    ]
  }},
  options: {{
    responsive: true,
    plugins: {{
      legend: {{ labels: {{ color:'#ccc' }} }},
      title:  {{ display:true,
                 text:'Violations per Time Segment (peak highlighted in bright red)',
                 color:'#ccc', font:{{size:13}} }}
    }},
    scales: {{
      x: {{ ticks:{{color:'#666'}}, grid:{{color:'#222'}},
            title:{{display:true,text:'Time Segment',color:'#666'}} }},
      y: {{ ticks:{{color:'#666'}}, grid:{{color:'#222'}},
            beginAtZero:true,
            title:{{display:true,text:'Unique Persons',color:'#666'}} }}
    }}
  }}
}});

new Chart(document.getElementById('combinedChart'), {{
  type: 'line',
  data: {{
    labels: ylabels,
    datasets: [
      {{ label:'Warning Zone', data:yvalues, borderColor:'#ffd600',
         backgroundColor:'#ffd60033', fill:true, tension:0.4,
         pointRadius:0, borderWidth:2 }},
      {{ label:'Violation Zone', data:rvalues, borderColor:'#e53935',
         backgroundColor:'#e5393533', fill:true, tension:0.4,
         pointRadius:0, borderWidth:2 }}
    ]
  }},
  options: {{
    responsive: true,
    plugins: {{ legend: {{ labels: {{ color:'#ccc' }} }},
               title: {{ display:true, text:'Combined Activity Timeline',
                          color:'#ccc', font:{{ size:14 }} }} }},
    scales: {{
      x: {{ ticks:{{ color:'#666', maxTicksLimit:10 }}, grid:{{ color:'#222' }},
            title:{{ display:true, text:'Time (s)', color:'#666' }} }},
      y: {{ ticks:{{ color:'#666' }}, grid:{{ color:'#222' }}, beginAtZero:true,
            title:{{ display:true, text:'Persons', color:'#666' }} }}
    }}
  }}
}});

// ── Trajectory canvas ──────────────────────────────────────────────────────
const trajData  = {traj_json};
const vidW      = {frame_w};
const vidH      = {frame_h};
const firstFrame= "{first_frame_b64}";

(function drawTrajectories() {{
  const canvas = document.getElementById('trajCanvas');
  if (!canvas) return;

  // Find actual data bounds so trajectories fill the canvas properly
  let minX = Infinity, maxX = -Infinity;
  let minY = Infinity, maxY = -Infinity;
  for (const pts of Object.values(trajData)) {{
    for (const p of pts) {{
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }}
  }}
  // Use video dimensions as bounds (most reliable)
  minX = 0; minY = 0;
  maxX = vidW; maxY = vidH;

  // Aspect-correct canvas
  const maxW   = Math.min(canvas.parentElement.clientWidth || 900, 1400);
  const aspect = vidH / vidW;
  canvas.width  = maxW;
  canvas.height = Math.round(maxW * aspect);

  const scaleX = canvas.width  / (maxX - minX);
  const scaleY = canvas.height / (maxY - minY);

  const ctx = canvas.getContext('2d');

  function render(bgLoaded) {{
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Background — first frame or dark fill
    if (bgLoaded && firstFrame) {{
      ctx.globalAlpha = 0.35;
      ctx.drawImage(bgLoaded, 0, 0, canvas.width, canvas.height);
      ctx.globalAlpha = 1.0;
    }} else {{
      ctx.fillStyle = '#0d0d14';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
    }}

    // Grid lines (subtle)
    ctx.strokeStyle = '#ffffff11';
    ctx.lineWidth   = 0.5;
    for (let gx = 0; gx < canvas.width; gx += canvas.width/8) {{
      ctx.beginPath(); ctx.moveTo(gx,0); ctx.lineTo(gx, canvas.height); ctx.stroke();
    }}
    for (let gy = 0; gy < canvas.height; gy += canvas.height/6) {{
      ctx.beginPath(); ctx.moveTo(0,gy); ctx.lineTo(canvas.width, gy); ctx.stroke();
    }}

    const zoneColor = {{ red:'#ff1744', yellow:'#ffd600', none:'#00e676' }};
    const dotColor  = {{ red:'#ff6b6b', yellow:'#ffe066', none:'#69ff9e' }};

    // Draw all trajectories
    for (const [oid, pts] of Object.entries(trajData)) {{
      if (pts.length < 2) continue;

      for (let i = 1; i < pts.length; i++) {{
        const p0 = pts[i-1], p1 = pts[i];
        const x0 = (p0.x - minX) * scaleX;
        const y0 = (p0.y - minY) * scaleY;
        const x1 = (p1.x - minX) * scaleX;
        const y1 = (p1.y - minY) * scaleY;

        ctx.beginPath();
        ctx.moveTo(x0, y0);
        ctx.lineTo(x1, y1);
        ctx.strokeStyle = zoneColor[p1.z] || zoneColor.none;
        ctx.lineWidth   = p1.z === 'red' ? 2.0 : 1.2;
        ctx.globalAlpha = p1.z === 'red' ? 0.9 : 0.6;
        ctx.stroke();
      }}

      // End-point dot
      const last = pts[pts.length - 1];
      const lx = (last.x - minX) * scaleX;
      const ly = (last.y - minY) * scaleY;
      ctx.beginPath();
      ctx.arc(lx, ly, p1z_dot_r(last.z), 0, Math.PI * 2);
      ctx.fillStyle   = dotColor[last.z] || dotColor.none;
      ctx.globalAlpha = 1.0;
      ctx.fill();
    }}

    // Legend
    const leg = [['#00e676','Safe'],['#ffd600','Warning'],['#ff1744','Violation']];
    let lx = 12, ly = canvas.height - 16;
    ctx.font = `${{Math.max(11, canvas.width/70)}}px Arial`;
    for (const [col, lbl] of leg) {{
      ctx.fillStyle   = col;
      ctx.globalAlpha = 1.0;
      ctx.fillRect(lx, ly - 10, 14, 10);
      ctx.fillStyle = '#ccc';
      ctx.fillText(lbl, lx + 18, ly);
      lx += ctx.measureText(lbl).width + 40;
    }}
  }}

  function p1z_dot_r(z) {{ return z === 'red' ? 4 : 3; }}

  // Load background image if available
  if (firstFrame) {{
    const img = new Image();
    img.onload  = () => render(img);
    img.onerror = () => render(null);
    img.src = 'data:image/jpeg;base64,' + firstFrame;
  }} else {{
    render(null);
  }}
}})();

</script>
</body>
</html>"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[INFO] HTML report saved: {report_path}")



# ─────────────────────────────────────────────────────────────────────────────
#  RISK SCORE ENGINE
# ─────────────────────────────────────────────────────────────────────────────
RISK_LOW    = 30
RISK_MEDIUM = 70

def compute_risk_score(zone_type, dwell_frames, fps,
                       speed_px_per_frame, nearby_count,
                       predicted_in_s):
    """
    Compute a 0-100+ danger score for one tracked person.
    Returns (score, label, colour)
    """
    score = 0

    # Current zone
    if zone_type == "yellow":
        score += 20
    elif zone_type == "red":
        score += 50

    # Dwell time in zone
    dwell_s = dwell_frames / fps if fps > 0 else 0
    if dwell_s > 5:
        score += 15
    elif dwell_s > 2:
        score += 8

    # Speed (fast movement = higher risk)
    if speed_px_per_frame > 8:
        score += 25
    elif speed_px_per_frame > 4:
        score += 12

    # Group density
    if nearby_count >= 4:
        score += 15
    elif nearby_count >= 2:
        score += 7

    # Predictive — will enter red zone soon
    if predicted_in_s is not None:
        if predicted_in_s < 1.5:
            score += 45
        elif predicted_in_s < 3.0:
            score += 30

    score = min(score, 100)

    if score >= RISK_MEDIUM:
        return score, "HIGH",   (0, 30, 220)    # red
    elif score >= RISK_LOW:
        return score, "MEDIUM", (0, 140, 255)   # orange
    else:
        return score, "LOW",    (50, 200, 50)   # green


def predict_zone_entry(kf_tracker, masks, zone_types, fps,
                       horizon_s=3.0):
    """
    Extrapolate Kalman state N frames ahead.
    Returns seconds until predicted RED zone entry, or None.
    """
    import copy, numpy as np
    horizon_f = int(fps * horizon_s)
    # Simulate Kalman forward without modifying the real tracker
    x = kf_tracker.kf_x.copy()
    F = kf_tracker.kf_F
    for step in range(1, horizon_f + 1):
        x = F @ x
        cx = int(x[0, 0] - x[2, 0] / 2 + x[2, 0] / 2)   # centre x
        cy = int(x[1, 0] + x[3, 0] / 2)                   # foot y
        cx = int(x[0, 0])
        cy = int(x[1, 0] + x[3, 0] / 2)
        for zi, mask in enumerate(masks):
            ztype = zone_types[zi] if zi < len(zone_types) else "red"
            if ztype != "red":
                continue
            cx_c = min(max(cx, 0), mask.shape[1] - 1)
            cy_c = min(max(cy, 0), mask.shape[0] - 1)
            if mask[cy_c, cx_c] > 0:
                return step / fps   # seconds until entry
    return None


def draw_risk_label(frame, box, score, label, colour, predicted_s,
                    dwell_s, u):
    """
    Draw compact risk info ABOVE the bounding box.
    All text is small (fs_small) and on one or two lines.
    """
    x, y, w, h = box
    fh, fw = frame.shape[:2]
    fs  = u["fs_small"]
    lw  = u["lw_thin"]
    pad = max(2, u["pad"] // 2)

    # Line 1: RISK score + label
    line1 = f"RISK:{score} {label}"
    (tw1, th1), _ = cv2.getTextSize(line1, FONT_SMALL, fs, lw)

    # Line 2: predicted or dwell
    if predicted_s is not None and label != "HIGH":
        line2 = f"~{predicted_s:.1f}s"
    elif dwell_s > 0.5:
        line2 = f"{dwell_s:.1f}s"
    else:
        line2 = None
    th2 = 0
    tw2 = 0
    if line2:
        (tw2, th2), _ = cv2.getTextSize(line2, FONT_SMALL, fs, lw)

    total_h = th1 + (th2 + pad if line2 else 0) + pad * 2
    max_tw  = max(tw1, tw2) if line2 else tw1
    bg_x0   = max(0, x)
    bg_x1   = min(fw, x + max_tw + pad * 2)
    bg_y1   = max(0, y - 2)
    bg_y0   = max(0, bg_y1 - total_h)

    # Background
    overlay = frame.copy()
    cv2.rectangle(overlay, (bg_x0, bg_y0), (bg_x1, bg_y1), (10, 10, 10), -1)
    cv2.addWeighted(overlay, 0.6, frame, 0.4, 0, frame)

    # Text line 1
    ty1 = bg_y0 + pad + th1
    cv2.putText(frame, line1, (bg_x0 + pad, ty1),
                FONT_SMALL, fs, colour, lw, cv2.LINE_AA)

    # Text line 2
    if line2:
        ty2 = ty1 + th2 + pad
        cv2.putText(frame, line2, (bg_x0 + pad, ty2),
                    FONT_SMALL, fs, (200, 200, 200), lw, cv2.LINE_AA)


# ─────────────────────────────────────────────────────────────────────────────
#  INTERACTIVE ZONE SELECTOR
# ─────────────────────────────────────────────────────────────────────────────
_pts  = []
_done = False

def _mouse_cb(event, x, y, flags, param):
    global _pts, _done
    if event == cv2.EVENT_LBUTTONDOWN and not _done:
        _pts.append((x, y))

def select_zone(frame, zone_idx=1, total=1, label=None):
    global _pts, _done
    _pts, _done = [], False
    cv2.destroyAllWindows()
    cv2.waitKey(1)

    fh, fw = frame.shape[:2]
    u = ui(fw, fh)
    zone_label = label or f"ZONE {zone_idx}/{total}"
    title = (f"{zone_label}  |  "
             "Left-click=add  ENTER=confirm  BACKSPACE=undo  ESC=skip")
    cv2.namedWindow(title, cv2.WINDOW_NORMAL)
    _fit_window(title, fw, fh)
    cv2.setMouseCallback(title, _mouse_cb)
    print(f"\n[ZONE EDITOR] Zone {zone_idx}/{total}: "
          "click points, ENTER to confirm, ESC to skip\n")

    while not _done:
        vis = frame.copy()
        for i, pt in enumerate(_pts):
            cv2.circle(vis, pt, u["dot_r"], C_RED, -1)
            cv2.circle(vis, pt, u["dot_r"]+3, C_ORANGE, u["lw_thin"])
            cv2.putText(vis, str(i+1),
                        (pt[0] + u["dot_r"]+4, pt[1] - u["dot_r"]),
                        FONT_SMALL, u["fs_medium"], C_WHITE,
                        u["lw_thin"], cv2.LINE_AA)
            if i > 0:
                cv2.line(vis, _pts[i-1], pt, C_RED, u["lw_thin"], cv2.LINE_AA)
        if len(_pts) >= 3:
            arr = np.array(_pts, np.int32)
            ov  = vis.copy()
            cv2.fillPoly(ov, [arr], C_ZONE_FILL)
            cv2.addWeighted(ov, 0.28, vis, 0.72, 0, vis)
            cv2.polylines(vis, [arr], True, C_RED, u["lw_thick"], cv2.LINE_AA)
            cv2.line(vis, _pts[-1], _pts[0], (80, 80, 200), u["lw_thin"], cv2.LINE_AA)
        cv2.imshow(title, vis)
        k = cv2.waitKey(30) & 0xFF
        if k == 13:
            if len(_pts) >= 3:
                _done = True
            else:
                print("[ZONE EDITOR] Need at least 3 points!")
        elif k == 27:
            cv2.destroyWindow(title)
            return None
        elif k in (8, 127):
            if _pts:
                print(f"[ZONE EDITOR] Removed {_pts.pop()}. Total: {len(_pts)}")
    cv2.destroyWindow(title)
    return _pts if len(_pts) >= 3 else None

def setup_zones(preview, zone_mode, n_zones, w, h):
    """
    Always draws TWO zones:
      Zone 0 = YELLOW (warning  — person approaching)
      Zone 1 = RED    (violation — person inside)
    Returns zones list and zone_types list ("yellow" or "red").
    """
    zones      = []
    zone_types = []

    if zone_mode == "custom":
        zone_defs = [
            ("YELLOW WARNING ZONE",   "Draw the WARNING zone (yellow) — person is approaching"),
            ("RED VIOLATION ZONE",    "Draw the VIOLATION zone (red)  — person has entered"),
        ]
        for zi, (label, hint) in enumerate(zone_defs):
            print(f"\n[ZONE EDITOR] {hint}")
            poly = select_zone(preview.copy(), zi+1, len(zone_defs), label=label)
            if poly:
                zones.append(poly)
                zone_types.append("yellow" if zi == 0 else "red")
                print(f"[INFO] {label} confirmed ({len(poly)} vertices)")
            else:
                print(f"[INFO] {label} skipped - using auto.")
                zones      += auto_zone(w, h, 1)
                zone_types += ["yellow" if zi == 0 else "red"]

    elif zone_mode == "full":
        zones      = [[(0,0),(w,0),(w,h),(0,h)], [(0,0),(w,0),(w,h),(0,h)]]
        zone_types = ["yellow", "red"]
    else:
        zones      = auto_zone(w, h, 2)
        zone_types = ["yellow", "red"]

    if not zones:
        zones      = auto_zone(w, h, 2)
        zone_types = ["yellow", "red"]

    return zones, zone_types

# ─────────────────────────────────────────────────────────────────────────────
#  DRAWING
# ─────────────────────────────────────────────────────────────────────────────
def draw_zones_overlay(frame, zones, u):
    for zi, poly in enumerate(zones):
        pts = np.array(poly, np.int32)
        fh, fw = frame.shape[:2]
        ov  = frame.copy()
        cv2.fillPoly(ov, [pts], C_ZONE_FILL)
        cv2.addWeighted(ov, u["zone_alpha"], frame, 1 - u["zone_alpha"], 0, frame)
        cv2.polylines(frame, [pts], True, C_RED, u["lw_thick"], cv2.LINE_AA)
        M = cv2.moments(pts)
        if M["m00"] != 0:
            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])
            label = f"FORBIDDEN ZONE {zi+1}"
            (lw, lh), _ = cv2.getTextSize(label, FONT_MAIN, u["fs_large"], u["lw_thin"])
            lx = max(u["pad"], min(cx - lw // 2, fw - lw - u["pad"]))
            ly = max(lh + u["pad"], min(cy, fh - u["pad"]))
            cv2.putText(frame, label, (lx, ly),
                        FONT_MAIN, u["fs_large"], C_WHITE, u["lw_thin"], cv2.LINE_AA)

def draw_person_safe(frame, box, u):
    x, y, w, h = box
    cv2.rectangle(frame, (x, y), (x+w, y+h), C_GREEN, u["lw_thin"], cv2.LINE_AA)

def draw_person_violation(frame, box, u):
    x, y, w, h = box
    cv2.rectangle(frame, (x, y), (x+w, y+h), C_RED, u["lw_thin"], cv2.LINE_AA)

def draw_person_warning(frame, box, u):
    """Yellow box — person in warning zone."""
    x, y, w, h = box
    cv2.rectangle(frame, (x, y), (x+w, y+h), C_YELLOW, u["lw_thin"], cv2.LINE_AA)

def draw_warning_banner(frame, n_warn, fidx, fps, pulse, u):
    """Yellow banner — warning zone occupied."""
    fh, fw = frame.shape[:2]
    bh     = u["alert_h"]
    intens = int(160 + 60 * pulse)
    cv2.rectangle(frame, (0, 0), (fw, bh), (15, 15, 5), -1)
    cv2.rectangle(frame, (0, bh), (fw, bh + max(1, bh//14)),
                  (0, intens, intens), -1)
    cv2.rectangle(frame, (0, 0), (bh, bh), (0, intens, intens), -1)
    cv2.putText(frame, "!", (max(2, bh//4), int(bh*0.82)),
                FONT_MAIN, u["fs_large"], C_WHITE, u["lw_thin"], cv2.LINE_AA)
    elapsed = fidx / fps if fps > 0 else 0
    msg = (f"  WARNING  |  Persons approaching zone: {n_warn}"
           f"  |  {str(timedelta(seconds=int(elapsed)))}  |  Frame: {fidx}")
    cv2.putText(frame, msg, (bh + u["pad"], int(bh * 0.75)),
                FONT_SMALL, u["fs_small"], (50, intens, intens),
                u["lw_thin"], cv2.LINE_AA)

def draw_alert_banner(frame, n_viol, fidx, fps, pulse, u):
    fh, fw = frame.shape[:2]
    bh     = u["alert_h"]
    intens = int(160 + 60 * pulse)
    cv2.rectangle(frame, (0, 0), (fw, bh), (15, 15, 20), -1)
    cv2.rectangle(frame, (0, bh), (fw, bh + max(1, bh//14)), (0, 0, intens), -1)
    cv2.rectangle(frame, (0, 0), (bh, bh), (0, 0, intens), -1)
    cv2.putText(frame, "!", (max(2, bh//4), int(bh*0.82)),
                FONT_MAIN, u["fs_large"], C_WHITE, u["lw_thin"], cv2.LINE_AA)
    elapsed = fidx / fps if fps > 0 else 0
    msg = (f"  VIOLATION DETECTED  |  Persons in zone: {n_viol}"
           f"  |  {str(timedelta(seconds=int(elapsed)))}  |  Frame: {fidx}")
    cv2.putText(frame, msg, (bh + u["pad"], int(bh * 0.75)),
                FONT_SMALL, u["fs_small"], (200, 200, intens),
                u["lw_thin"], cv2.LINE_AA)

def draw_hud(frame, fidx, total, fps, n_people, n_viol,
             n_zones, model_name, total_viol, conf, u):
    fh, fw = frame.shape[:2]
    hh  = u["hud_h"]
    y0  = fh - hh
    pad = u["pad"]
    cv2.rectangle(frame, (0, y0), (fw, fh), C_PANEL_BG, -1)
    cv2.rectangle(frame, (0, y0), (fw, y0 + max(1, hh//18)), (60, 60, 80), -1)
    elapsed = fidx / fps if fps > 0 else 0
    total_t = total / fps if fps > 0 else 0
    segs = [
        ("MODEL",     model_name),
        ("FRAME",     f"{fidx}/{total}"),
        ("TIME",      f"{elapsed:.1f}s / {total_t:.1f}s"),
        ("FPS",       f"{fps:.1f}"),
        ("CONF",      f"{conf:.0%}"),
        ("PEOPLE",    str(n_people)),
        ("ZONES",     str(n_zones)),
        ("VIOLATORS", str(n_viol)),
        ("TOTAL",     str(total_viol)),
    ]
    seg_w = fw // len(segs)
    for i, (key, val) in enumerate(segs):
        x = i * seg_w + pad
        cv2.putText(frame, key, (x, y0 + int(hh * 0.38)),
                    FONT_SMALL, u["fs_small"], (130, 130, 160),
                    u["lw_thin"], cv2.LINE_AA)
        color = (C_RED if key in ("VIOLATORS", "TOTAL") and int(val or "0") > 0
                 else C_LIGHT_GRAY)
        cv2.putText(frame, val, (x, y0 + int(hh * 0.82)),
                    FONT_MAIN, u["fs_medium"], color,
                    u["lw_thin"], cv2.LINE_AA)
    pb = int(fw * fidx / max(total, 1))
    cv2.rectangle(frame, (0, fh - max(2, hh//16)), (pb, fh), C_RED, -1)


# ─────────────────────────────────────────────────────────────────────────────
#  TEMPORAL PATTERN ANALYZER
#  Splits video into fixed-length segments and counts violations per segment.
#  Works with any video length — segments auto-size to give ~8-12 bars.
# ─────────────────────────────────────────────────────────────────────────────
class TemporalAnalyzer:
    def __init__(self, total_frames, fps, n_segments=10):
        self.fps          = fps
        self.total_frames = total_frames
        self.n_seg        = max(1, min(n_segments, int(total_frames / max(fps, 1))))
        self.seg_len      = max(1, total_frames // self.n_seg)
        # Each segment: {"yellow": set of oids, "red": set of oids}
        self.segments     = [{"yellow": set(), "red": set()}
                             for _ in range(self.n_seg + 1)]

    def record(self, frame_idx, oid, zone_type):
        seg = min(frame_idx // self.seg_len, self.n_seg)
        if zone_type == "yellow":
            self.segments[seg]["yellow"].add(oid)
        elif zone_type == "red":
            self.segments[seg]["red"].add(oid)

    def get_results(self):
        """
        Returns list of dicts:
          {label, start_s, end_s, yellow_count, red_count, peak}
        """
        results = []
        peak_red = max((len(s["red"]) for s in self.segments), default=0)
        for i, seg in enumerate(self.segments):
            start_s = i * self.seg_len / self.fps
            end_s   = min((i+1) * self.seg_len / self.fps,
                          self.total_frames / self.fps)
            rc = len(seg["red"])
            yc = len(seg["yellow"])
            if start_s >= self.total_frames / self.fps:
                continue
            results.append({
                "label":        f"{start_s:.0f}s-{end_s:.0f}s",
                "start_s":      round(start_s, 1),
                "end_s":        round(end_s, 1),
                "yellow_count": yc,
                "red_count":    rc,
                "peak":         rc == peak_red and rc > 0,
            })
        return results


# ─────────────────────────────────────────────────────────────────────────────
#  PERSON RE-IDENTIFICATION
#  Matches re-appearing people by HSV color histogram of their bounding box.
#  Prevents double-counting of the same person as multiple unique violators.
# ─────────────────────────────────────────────────────────────────────────────
class PersonReID:
    """
    Color-histogram based re-identification.
    When a tracked ID disappears and a new ID appears with a similar
    color signature, they are linked as the same person.
    """
    HIST_BINS    = 32     # bins per HSV channel (H only used)
    MATCH_THRESH = 0.75   # Bhattacharyya similarity threshold

    def __init__(self):
        self.signatures   = {}   # oid -> np.array histogram
        self.reid_map     = {}   # new_oid -> original_oid
        self.lost_sigs    = []   # [(hist, original_oid)] for recently lost tracks

    def _compute_hist(self, frame_bgr, box):
        """Compute HSV hue histogram for the upper 2/3 of the bounding box."""
        x, y, w, h = box
        fh, fw = frame_bgr.shape[:2]
        x  = max(0, x);  y  = max(0, y)
        x2 = min(fw, x+w); y2 = min(fh, y + int(h * 0.67))
        if x2 <= x or y2 <= y:
            return None
        roi = frame_bgr[y:y2, x:x2]
        if roi.size == 0:
            return None
        hsv  = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
        hist = cv2.calcHist([hsv], [0], None, [self.HIST_BINS], [0, 180])
        cv2.normalize(hist, hist, 0, 1, cv2.NORM_MINMAX)
        return hist.flatten()

    def update(self, frame_bgr, tracked_boxes, active_oids):
        """
        Call every detection frame.
        tracked_boxes: dict oid -> (x,y,w,h)
        active_oids: set of currently tracked oids
        Returns reid_map: {new_oid: original_oid}
        """
        # Compute signatures for active tracks
        for oid, box in tracked_boxes.items():
            hist = self._compute_hist(frame_bgr, box)
            if hist is not None:
                self.signatures[oid] = hist

        # Find lost tracks (had signature, no longer active)
        newly_lost = [(oid, sig) for oid, sig in self.signatures.items()
                      if oid not in active_oids
                      and oid not in [o for _, o in self.lost_sigs]]
        self.lost_sigs.extend([(sig, oid) for oid, sig in newly_lost])
        # Keep only last 60 lost signatures
        self.lost_sigs = self.lost_sigs[-60:]

        # Try to match new tracks to lost ones
        new_oids = [oid for oid in active_oids
                    if oid not in self.signatures or
                    oid not in self.reid_map.values()]

        for oid in new_oids:
            if oid in self.reid_map:
                continue
            hist = self.signatures.get(oid)
            if hist is None:
                continue
            best_score = 0.0
            best_orig  = None
            for lost_hist, orig_oid in self.lost_sigs:
                score = cv2.compareHist(
                    hist.reshape(-1, 1).astype(np.float32),
                    lost_hist.reshape(-1, 1).astype(np.float32),
                    cv2.HISTCMP_BHATTACHARYYA)
                # Bhattacharyya: lower = more similar; convert to similarity
                similarity = 1.0 - score
                if similarity > self.MATCH_THRESH and similarity > best_score:
                    best_score = similarity
                    best_orig  = orig_oid

            if best_orig is not None:
                self.reid_map[oid] = best_orig

        return dict(self.reid_map)

    def resolve(self, oid):
        """Return the original oid if this is a re-identified person."""
        return self.reid_map.get(oid, oid)

    def is_reid(self, oid):
        return oid in self.reid_map



# ─────────────────────────────────────────────────────────────────────────────
#  LIVE STATISTICS DASHBOARD
#  Semi-transparent panel in top-left corner.
#  Fully relative sizing — works on any resolution/orientation.
# ─────────────────────────────────────────────────────────────────────────────
def draw_live_dashboard(frame, frame_idx, fps, total_frames,
                        n_people, n_viol, n_yellow,
                        total_viol, dash_history, u):
    """
    Draws a compact semi-transparent dashboard in the top-left corner.
    Contains:
      - Scene risk level (LOW/MEDIUM/HIGH) with colour indicator
      - Current counts: people, yellow warnings, red violations
      - Total violations counter
      - Mini sparkline bar chart of recent violations (last 30s)
      - Trend arrow (increasing/stable/decreasing)
    """
    fh, fw = frame.shape[:2]
    md = min(fw, fh)

    # Dashboard dimensions — relative to frame
    dash_w  = int(fw * 0.22)
    dash_w  = max(160, min(dash_w, 320))
    pad     = max(4, md // 120)
    lh      = max(16, md // 38)
    n_rows  = 7
    chart_h = max(30, md // 22)
    margin  = int(md * 0.012)

    # ── Scene risk level ─────────────────────────────────────────────────────
    if n_viol > 0:
        scene_risk  = "HIGH"
        risk_colour = (0, 30, 220)
        risk_bg     = (0, 0, 80)
    elif n_yellow > 0:
        scene_risk  = "MEDIUM"
        risk_colour = (0, 140, 255)
        risk_bg     = (0, 40, 80)
    else:
        scene_risk  = "LOW"
        risk_colour = (50, 200, 50)
        risk_bg     = (0, 50, 0)

    # Measure banner height FIRST so dash_h is computed correctly
    label_risk = f"SCENE RISK: {scene_risk}"
    (rw, rh), _ = cv2.getTextSize(label_risk, FONT_SMALL, u["fs_small"], 1)
    banner_h = rh + pad * 2

    # Now compute total dashboard height dynamically
    dash_h = banner_h + n_rows * (lh + pad) + chart_h + pad * 4

    alert_h = u["alert_h"]
    top = alert_h + margin

    x0, y0 = margin, top
    x1, y1 = x0 + dash_w, top + dash_h
    x1 = min(x1, fw - margin)
    y1 = min(y1, fh - u["hud_h"] - margin)

    # Semi-transparent background — drawn with final dimensions
    overlay = frame.copy()
    cv2.rectangle(overlay, (x0, y0), (x1, y1), (10, 10, 18), -1)
    cv2.rectangle(overlay, (x0, y0), (x1, y1), (60, 60, 80), 1)
    cv2.addWeighted(overlay, 0.55, frame, 0.45, 0, frame)

    # Risk banner
    cv2.rectangle(frame, (x0, y0), (x1, y0 + banner_h), risk_bg, -1)
    rx = x0 + max(pad, (dash_w - rw) // 2)
    ry = y0 + pad + rh
    cv2.putText(frame, label_risk, (rx, ry),
                FONT_SMALL, u["fs_small"], risk_colour, 1, cv2.LINE_AA)

    # ── Stats rows ──────────────────────────────────────────────────────────
    fs   = u["fs_small"]
    rows = [
        ("PEOPLE",    str(n_people),    C_LIGHT_GRAY),
        ("WARNING",   str(n_yellow),    C_YELLOW if n_yellow > 0 else C_LIGHT_GRAY),
        ("VIOLATION", str(n_viol),      C_RED    if n_viol   > 0 else C_LIGHT_GRAY),
        ("TOTAL",     str(total_viol),  C_RED    if total_viol > 0 else C_LIGHT_GRAY),
        ("TIME",      f"{frame_idx/fps:.1f}s" if fps > 0 else "0s", C_LIGHT_GRAY),
    ]

    # Auto-expand panel width to fit longest value
    max_val_w = 0
    for key, val, _ in rows:
        (kw, _), _ = cv2.getTextSize(key, FONT_SMALL, fs, 1)
        (vw, _), _ = cv2.getTextSize(val, FONT_MAIN,  fs, 1)
        needed = kw + vw + pad * 4
        if needed > max_val_w:
            max_val_w = needed
    if x0 + max_val_w > x1:
        x1 = min(x0 + max_val_w, fw - margin)

    cy = y0 + banner_h + lh + pad
    for key, val, col in rows:
        # Key
        cv2.putText(frame, key, (x0 + pad, cy),
                    FONT_SMALL, fs, (120, 120, 150), 1, cv2.LINE_AA)
        # Value right-aligned within panel
        (vw, _), _ = cv2.getTextSize(val, FONT_MAIN, fs, 1)
        cv2.putText(frame, val, (x1 - vw - pad, cy),
                    FONT_MAIN, fs, col, 1, cv2.LINE_AA)
        cy += lh + pad

    # ── Trend arrow ─────────────────────────────────────────────────────────
    if len(dash_history) >= 10:
        recent  = [h[1] for h in dash_history[-10:]]
        older   = [h[1] for h in dash_history[-20:-10]] if len(dash_history) >= 20 else recent
        avg_r   = sum(recent) / len(recent)
        avg_o   = sum(older)  / len(older)
        if avg_r > avg_o + 0.3:
            trend, t_col = "RISING  ^", (0, 30, 220)
        elif avg_r < avg_o - 0.3:
            trend, t_col = "FALLING v", (50, 200, 50)
        else:
            trend, t_col = "STABLE  -", C_LIGHT_GRAY
        cv2.putText(frame, trend, (x0 + pad, cy),
                    FONT_SMALL, fs, t_col, 1, cv2.LINE_AA)
        cy += lh + pad

    # ── Mini sparkline bar chart ─────────────────────────────────────────────
    if dash_history:
        chart_y0 = cy + pad
        chart_y1 = chart_y0 + chart_h
        chart_x0 = x0 + pad
        chart_x1 = x1 - pad
        chart_w  = chart_x1 - chart_x0

        # Sample last N points to fit the chart width
        n_bars   = min(len(dash_history), chart_w // 3)
        if n_bars > 1:
            step    = max(1, len(dash_history) // n_bars)
            samples = [dash_history[i] for i in
                       range(len(dash_history) - n_bars * step,
                             len(dash_history), step)][-n_bars:]
            max_val = max((s[1] + s[2] for s in samples), default=1)
            max_val = max(max_val, 1)
            bar_w   = max(1, chart_w // len(samples))

            # Chart background
            cv2.rectangle(frame, (chart_x0, chart_y0),
                          (chart_x1, chart_y1), (20, 20, 30), -1)

            for i, (_, nr, ny) in enumerate(samples):
                bx    = chart_x0 + i * bar_w
                # Red bar
                rh_px = int((nr / max_val) * chart_h)
                if rh_px > 0:
                    cv2.rectangle(frame,
                                  (bx, chart_y1 - rh_px),
                                  (bx + max(1, bar_w-1), chart_y1),
                                  (0, 30, 180), -1)
                # Yellow bar on top
                yh_px = int((ny / max_val) * chart_h)
                if yh_px > 0:
                    cv2.rectangle(frame,
                                  (bx, chart_y1 - rh_px - yh_px),
                                  (bx + max(1, bar_w-1), chart_y1 - rh_px),
                                  (0, 180, 220), -1)

            # Chart label — inside chart, top-left corner
            cv2.putText(frame, "last 30s", (chart_x0 + 2, chart_y0 + 9),
                        FONT_SMALL, fs * 0.75, (100, 100, 130), 1, cv2.LINE_AA)

# ─────────────────────────────────────────────────────────────────────────────
#  PRODUCER THREAD  — YOLO + Kalman + annotate -> queue
# ─────────────────────────────────────────────────────────────────────────────
def _producer(input_path, output_path, model_name,
              zones, masks, zone_types, conf_thresh,
              detect_scale, detect_every,
              csv_path, frame_q, stop_event,
              stats_out):
    """
    stats_out: dict passed by reference — filled with stats for HTML report.
    zone_types: list of "yellow" or "red" per zone index.
    """
    try:
        model  = YOLO(model_name)
        cap    = cv2.VideoCapture(input_path)
        orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps    = cap.get(cv2.CAP_PROP_FPS) or 24.0
        total  = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        dw     = int(orig_w * detect_scale)
        dh     = int(orig_h * detect_scale)

        writer = None
        if output_path:
            fourcc = cv2.VideoWriter_fourcc(*"mp4v")
            writer = cv2.VideoWriter(output_path, fourcc, fps, (dw, dh))

        tracker         = CentroidTracker(max_disappeared=1,
                                          max_distance=int(min(dw, dh) * 0.08))
        kalman_trackers = {}
        violation_start = {}
        total_viol      = 0
        logged_viol     = set()
        KalmanBoxTracker.count = 0

        # Email config
        email_cfg          = _load_email_config()
        last_email_frame   = -9999   # prevent spam — min 10s between emails
        email_cooldown_f   = int(fps * 10)
        if email_cfg and all(email_cfg.values()):
            print(f"[EMAIL] Config loaded — notifications active")
            print(f"[EMAIL] From: {email_cfg['sender']}  To: {email_cfg['receiver']}")
        else:
            print("[EMAIL] No config found or incomplete — notifications disabled")

        # Heatmap + stats accumulators
        heatmap          = Heatmap(dh, dw)
        first_frame_img  = None
        yellow_timeline  = []   # (time_s, n_in_yellow)
        red_timeline     = []   # (time_s, n_in_red)
        unique_people    = set()
        unique_yellow    = set()
        unique_red       = set()
        timeline_every   = max(1, int(fps))   # record every second

        # Temporal Pattern Analyzer
        temporal         = TemporalAnalyzer(total, fps, n_segments=10)

        # Person Re-identification
        reid             = PersonReID()
        reid_log         = {}   # orig_oid -> return count

        # Trajectory storage for HTML report
        # trajectories[oid] = [(frame_idx, cx, cy, zone_type), ...]
        trajectories     = defaultdict(list)
        TRAJ_MAX_POINTS  = 500   # max points per person (memory cap)

        # Live dashboard history (last 30 seconds of violation counts)
        dash_history     = []    # [(frame_idx, n_red, n_yellow)]
        DASH_HISTORY_LEN = int(fps * 30)

        csv_file = csv_writer = None
        if csv_path:
            csv_file   = open(csv_path, "w", newline="")
            csv_writer = csv.writer(csv_file)
            csv_writer.writerow(["timestamp", "frame", "time_s", "person_id",
                                 "zone_index", "bbox_x", "bbox_y",
                                 "bbox_w", "bbox_h", "confidence",
                                 "duration_in_zone_s"])

        frame_idx    = 0
        last_tracked = {}   # oid -> last known violation state
        last_confs   = {}

        while not stop_event.is_set():
            ret, frame = cap.read()
            if not ret:
                break
            frame_idx += 1
            proc = cv2.resize(frame, (dw, dh))
            u_f  = ui(dw, dh)

            # Save first frame as heatmap background
            if first_frame_img is None:
                first_frame_img = proc.copy()

            is_detect = (frame_idx % detect_every == 0) or (frame_idx == 1)

            if is_detect:
                results = model(proc, classes=[0], conf=conf_thresh, verbose=False)
                boxes, confs = [], []
                for r in results:
                    for box in r.boxes:
                        x1, y1, x2, y2 = map(int, box.xyxy[0])
                        w2, h2 = x2-x1, y2-y1
                        if w2 > 8 and h2 > 16:
                            boxes.append((x1, y1, w2, h2))
                            confs.append(float(box.conf[0]))

                centroids, tracked = tracker.update(boxes)

                # Update Kalman trackers
                active = set(tracked.keys())
                for oid, box in tracked.items():
                    if oid not in kalman_trackers:
                        kalman_trackers[oid] = KalmanBoxTracker(box)
                    else:
                        kalman_trackers[oid].update(box)
                for oid in list(kalman_trackers):
                    if oid not in active:
                        del kalman_trackers[oid]

                # Dual-zone check: RED has priority over YELLOW
                # Strategy: check ALL zones the person is in, assign highest priority
                # Priority: red > yellow > none
                violators    = {}   # oid -> zone_idx (highest priority zone)
                yellow_now   = set()
                red_now      = set()
                for oid, box in tracked.items():
                    unique_people.add(oid)
                    best_zi    = -1
                    best_prio  = -1   # 0=yellow, 1=red
                    for zi, mask in enumerate(masks):
                        if feet_in_zone(box, mask):
                            ztype = zone_types[zi] if zi < len(zone_types) else "red"
                            prio  = 1 if ztype == "red" else 0
                            if prio > best_prio:
                                best_prio = prio
                                best_zi   = zi
                    if best_zi >= 0:
                        violators[oid] = best_zi
                        ztype = zone_types[best_zi] if best_zi < len(zone_types) else "red"
                        if ztype == "yellow":
                            yellow_now.add(oid)
                            unique_yellow.add(oid)
                        else:
                            red_now.add(oid)
                            unique_red.add(oid)
                        if oid not in violation_start:
                            violation_start[oid] = frame_idx
                            total_viol += 1
                    else:
                        violation_start.pop(oid, None)

                # Record timeline every second
                if frame_idx % timeline_every == 0:
                    t_s = frame_idx / fps
                    yellow_timeline.append((t_s, len(yellow_now)))
                    red_timeline.append((t_s, len(red_now)))

                # Heatmap: accumulate foot positions
                heatmap.add(list(tracked.values()))

                # Person Re-identification
                reid_map = reid.update(proc, tracked, set(tracked.keys()))
                # Record re-appearances
                for new_oid, orig_oid in reid_map.items():
                    if orig_oid != new_oid:
                        reid_log[orig_oid] = reid_log.get(orig_oid, 0) + 1

                # Temporal pattern recording
                for oid in yellow_now:
                    temporal.record(frame_idx, reid.resolve(oid), "yellow")
                for oid in red_now:
                    temporal.record(frame_idx, reid.resolve(oid), "red")

                # Record trajectories for HTML report
                # Use FOOT POINT (bottom-centre) — shows real ground position
                # and gives perspective-correct trajectories in the scene
                for oid, box in tracked.items():
                    cx_t = box[0] + box[2] // 2        # horizontal centre
                    cy_t = box[1] + box[3]             # bottom edge (feet)
                    zi   = violators.get(oid, -1)
                    zt   = (zone_types[zi] if zi >= 0 and zi < len(zone_types)
                            else "none")
                    traj = trajectories[reid.resolve(oid)]
                    if len(traj) < TRAJ_MAX_POINTS:
                        traj.append((frame_idx, cx_t, cy_t, zt))

                # Build conf map
                def get_conf(oid):
                    c = centroids.get(oid)
                    if c is None or not confs: return 0.0
                    best, bi = float("inf"), 0
                    for i, b in enumerate(boxes):
                        d = math.hypot(c[0]-(b[0]+b[2]//2), c[1]-(b[1]+b[3]//2))
                        if d < best: best, bi = d, i
                    return confs[bi] if bi < len(confs) else 0.0

                last_tracked = {}
                for oid, box in tracked.items():
                    cf    = get_conf(oid)
                    dur   = ((frame_idx - violation_start[oid]) / fps
                             if oid in violators else 0.0)
                    zi    = violators.get(oid, -1)
                    ztype = (zone_types[zi] if zi >= 0 and zi < len(zone_types)
                             else "none")
                    last_tracked[oid] = {
                        "in_zone":   oid in violators,
                        "zone_idx":  zi,
                        "zone_type": ztype,
                        "conf":      cf,
                        "dur":       dur,
                    }
                    if csv_writer and oid in violators:
                        log_key = (oid, frame_idx // int(fps))
                        if log_key not in logged_viol:
                            logged_viol.add(log_key)
                            x, y, w2, h2 = box
                            csv_writer.writerow([
                                datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                                frame_idx, round(frame_idx/fps, 2),
                                oid, violators[oid]+1, x, y, w2, h2,
                                round(cf, 3), round(dur, 2)])

            # Every frame: advance Kalman + annotate
            n_viol_now  = 0
            current_boxes = {}
            for oid, kf in kalman_trackers.items():
                box = kf.predict()
                cx  = box[0] + box[2] // 2
                cy  = box[1] + box[3] // 2
                if not (0 <= cx < dw and 0 <= cy < dh):
                    continue
                if box[2] < 4 or box[3] < 4:
                    continue
                current_boxes[oid] = box

            # Draw boxes with Risk Score + Predictive labels
            n_yellow_now = 0
            for oid, box in current_boxes.items():
                info   = last_tracked.get(oid, {})
                ztype  = info.get("zone_type", "none")
                dwell_s = info.get("dur", 0.0)

                # Speed from Kalman velocity
                kf = kalman_trackers.get(oid)
                speed = 0.0
                if kf is not None:
                    vx = float(kf.kf_x[4, 0])
                    vy = float(kf.kf_x[5, 0])
                    speed = math.hypot(vx, vy)

                # Nearby count (people within 80px)
                cx_o = box[0] + box[2] // 2
                cy_o = box[1] + box[3] // 2
                nearby = sum(
                    1 for o2, b2 in current_boxes.items()
                    if o2 != oid and
                    math.hypot((b2[0]+b2[2]//2)-cx_o,
                               (b2[1]+b2[3]//2)-cy_o) < 80
                )

                # Predictive — only for non-red people
                pred_s = None
                if ztype != "red" and kf is not None:
                    pred_s = predict_zone_entry(kf, masks, zone_types,
                                                fps, horizon_s=3.0)

                # Risk score
                score, rlabel, rcolour = compute_risk_score(
                    ztype, int(dwell_s * fps), fps,
                    speed, nearby, pred_s)

                # Zone overrides risk label — zone is ground truth
                if ztype == "red":
                    rlabel  = "HIGH"
                    rcolour = (0, 30, 220)      # red
                    draw_person_violation(proc, box, u_f)
                    n_viol_now += 1
                elif ztype == "yellow":
                    # Yellow zone minimum MEDIUM
                    if rlabel == "LOW":
                        rlabel  = "MEDIUM"
                        rcolour = (0, 140, 255)  # orange
                    draw_person_warning(proc, box, u_f)
                    n_yellow_now += 1
                elif pred_s is not None and pred_s < 3.0:
                    # Predicted violation — orange box, minimum MEDIUM
                    if rlabel == "LOW":
                        rlabel  = "MEDIUM"
                        rcolour = (0, 140, 255)
                    x2, y2, w2, h2 = box
                    cv2.rectangle(proc, (x2, y2), (x2+w2, y2+h2),
                                  C_ORANGE, u_f["lw_thin"], cv2.LINE_AA)
                else:
                    rlabel  = "LOW"
                    rcolour = (50, 200, 50)     # green
                    score   = min(score, RISK_LOW - 1)
                    draw_person_safe(proc, box, u_f)

                # Risk label above box — colour always matches box
                draw_risk_label(proc, box, score, rlabel, rcolour,
                                pred_s, dwell_s, u_f)

                # RE-ID works in background for accurate counting
                # No visual badge on frame — results shown in HTML report only

            # Update dashboard history
            dash_history.append((frame_idx, n_viol_now, n_yellow_now))
            if len(dash_history) > DASH_HISTORY_LEN:
                dash_history.pop(0)

            # Email notification — AFTER draw loop so n_viol_now is correct
            if n_viol_now > 0 and (frame_idx - last_email_frame) >= email_cooldown_f:
                last_email_frame = frame_idx
                high_count = sum(
                    1 for oid in current_boxes
                    if last_tracked.get(oid, {}).get("zone_type") == "red"
                )
                risk_txt = (f"{high_count} person(s) in RED violation zone — "
                            f"Frame {frame_idx}")
                print(f"[EMAIL] Sending alert — {risk_txt}")
                send_violation_email(email_cfg, proc.copy(),
                                     frame_idx, fps, n_viol_now, risk_txt)

            # Alert banner — red takes priority over yellow
            if n_viol_now:
                pulse = (math.sin(frame_idx * 0.25) + 1) / 2
                draw_alert_banner(proc, n_viol_now, frame_idx, fps, pulse, u_f)
            elif n_yellow_now:
                pulse = (math.sin(frame_idx * 0.25) + 1) / 2
                draw_warning_banner(proc, n_yellow_now, frame_idx, fps, pulse, u_f)

            # Live statistics dashboard (top-left, semi-transparent)
            draw_live_dashboard(proc, frame_idx, fps, total,
                                len(current_boxes), n_viol_now, n_yellow_now,
                                total_viol, dash_history, u_f)

            # HUD
            draw_hud(proc, frame_idx, total, fps,
                     len(current_boxes), n_viol_now, len(zones),
                     model_name, total_viol, conf_thresh, u_f)

            if writer:
                writer.write(proc)

            # Push to display queue (block if full — this is the throttle)
            frame_q.put(("frame", proc, fps))

        cap.release()
        if writer:
            writer.release()
        if csv_file:
            csv_file.close()

        # Fill stats for report
        def peak(tl):
            if not tl: return 0.0, 0
            t, c = max(tl, key=lambda x: x[1])
            return t, c
        pt_y, pc_y = peak(yellow_timeline)
        pt_r, pc_r = peak(red_timeline)
        # Unique people after ReID correction
        unique_people_reid = set(reid.resolve(o) for o in unique_people)
        unique_red_reid    = set(reid.resolve(o) for o in unique_red)

        # Serialize trajectories for HTML (sample to keep size reasonable)
        traj_serialized = {}
        for oid, pts in trajectories.items():
            # Sample max 100 points per person
            step = max(1, len(pts) // 100)
            traj_serialized[str(oid)] = [
                {"f": p[0], "x": p[1], "y": p[2], "z": p[3]}
                for p in pts[::step]
            ]

        stats_out.update({
            "yellow_timeline":    yellow_timeline,
            "red_timeline":       red_timeline,
            "total_people":       len(unique_people_reid),
            "total_yellow":       len(unique_yellow),
            "total_red":          len(unique_red_reid),
            "peak_yellow_time":   pt_y,
            "peak_yellow_count":  pc_y,
            "peak_red_time":      pt_r,
            "peak_red_count":     pc_r,
            "fps":                fps,
            "total_frames":       total,
            "duration_s":         total / fps if fps > 0 else 0,
            "heatmap_obj":        heatmap,
            "first_frame_img":    first_frame_img,
            "temporal_segments":  temporal.get_results(),
            "reid_returns":       sum(reid_log.values()),
            "reid_unique":        len(reid_log),
            "trajectories":       traj_serialized,
            "frame_w":            dw,
            "frame_h":            dh,
        })

        frame_q.put(("done", None, None))

    except Exception as exc:
        frame_q.put(("error", exc, None))

# ─────────────────────────────────────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────────────────────────────────────
def run(
    input_path   = None,
    output_path  = None,
    model_name   = "yolov8n.pt",
    zone_mode    = "custom",
    n_zones      = 1,
    conf_thresh  = 0.40,
    detect_scale = DETECT_SCALE,
    detect_every = DETECT_EVERY,
    csv_log      = True,
    save_video   = True,
):
    # 1. File picker
    if not input_path:
        print("\n[SETUP] Select your video file...")
        input_path = pick_video_file()
    if not input_path or not os.path.isfile(input_path):
        print("[ERROR] No valid video selected.")
        sys.exit(1)

    # 2. Output path (optional)
    if save_video and output_path is None:
        auto_out    = os.path.splitext(input_path)[0] + "_detected.mp4"
        output_path = pick_output_file(auto_out)
        # If user cancelled save dialog -> no output file
    csv_path = (os.path.splitext(input_path)[0] + "_violations.csv"
                if csv_log else None)

    print(f"\n[INFO] Input        : {input_path}")
    print(f"[INFO] Output       : {output_path or 'not saving'}")
    print(f"[INFO] Detect every : {detect_every} frames (Kalman fills the rest)")
    print(f"[INFO] Detect scale : {detect_scale}")

    # 3. Probe video
    cap = cv2.VideoCapture(input_path)
    if not cap.isOpened():
        print(f"[ERROR] Cannot open {input_path}")
        sys.exit(1)
    orig_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    orig_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps    = cap.get(cv2.CAP_PROP_FPS) or 24.0
    ret, first = cap.read()
    cap.release()
    if not ret:
        print("[ERROR] Cannot read first frame.")
        sys.exit(1)

    dw = int(orig_w * detect_scale)
    dh = int(orig_h * detect_scale)
    print(f"[INFO] Original     : {orig_w}x{orig_h}  "
          f"({'portrait' if orig_h > orig_w else 'landscape'})")
    print(f"[INFO] Process size : {dw}x{dh}   FPS: {fps:.2f}")

    # 4. Zone setup — always fresh, clean preview frame
    cv2.destroyAllWindows(); cv2.waitKey(1)
    preview              = cv2.resize(first, (dw, dh)).copy()
    zones, zone_types    = setup_zones(preview, zone_mode, n_zones, dw, dh)
    masks                = [build_mask(dh, dw, z) for z in zones]
    cv2.destroyAllWindows(); cv2.waitKey(1)

    print(f"\n[INFO] {len(zones)} forbidden zone(s) active.")
    print("[INFO] Starting live analysis... (Q=quit  SPACE=pause)\n")

    # 5. Launch producer thread
    frame_q    = queue.Queue(maxsize=QUEUE_SIZE)
    stop_event = threading.Event()

    stats_out = {}   # filled by producer, used for report after loop

    producer = threading.Thread(
        target=_producer,
        args=(input_path, output_path, model_name,
              zones, masks, zone_types, conf_thresh,
              detect_scale, detect_every,
              csv_path, frame_q, stop_event, stats_out),
        daemon=True)
    producer.start()

    # 6. Display loop (main thread) — reads at native FPS
    win            = "Forbidden Zone Detector  |  Q=quit  SPACE=pause"
    paused         = False
    frame          = None
    window_created = False

    while True:
        if not paused:
            try:
                tag, data, vid_fps = frame_q.get(timeout=5.0)
            except queue.Empty:
                break

            if tag == "done":
                break
            elif tag == "error":
                print(f"\n[ERROR] {data}")
                break
            elif tag == "frame":
                frame = data

        if frame is not None:
            # Create/resize window only when we have the first real frame
            fh_f, fw_f = frame.shape[:2]
            if not window_created:
                cv2.namedWindow(win, cv2.WINDOW_NORMAL)
                _fit_window(win, fw_f, fh_f)
                window_created = True
            cv2.imshow(win, frame)

        # Native FPS delay
        delay = max(1, int(1000.0 / fps))
        k = cv2.waitKey(delay) & 0xFF
        if k in (ord('q'), 27):
            print("[INFO] Stopped by user.")
            stop_event.set()
            break
        elif k == ord(' '):
            paused = not paused
            print("[INFO] " + ("Paused." if paused else "Resumed."))

    stop_event.set()
    producer.join(timeout=3)
    cv2.destroyAllWindows()

    print(f"\n[INFO] Analysis finished.")
    if output_path and os.path.isfile(output_path):
        print(f"[INFO] Saved: {output_path}")
    if csv_path and os.path.isfile(csv_path):
        print(f"[INFO] CSV:   {csv_path}")

    # Generate heatmap PNG + HTML report
    base_name    = os.path.splitext(input_path)[0]
    heatmap_path = base_name + "_heatmap.png"
    report_path  = base_name + "_report.html"

    heatmap_obj     = stats_out.get("heatmap_obj")
    first_frame_img = stats_out.get("first_frame_img")

    if heatmap_obj is not None and first_frame_img is not None:
        heatmap_obj.save_png(heatmap_path, first_frame_img)

    stats_out["video_name"]   = os.path.basename(input_path)
    stats_out["generated_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        generate_html_report(report_path, heatmap_path, stats_out)
        import webbrowser
        webbrowser.open(report_path)
        print(f"[INFO] Report opened in browser: {report_path}")
    except Exception as e:
        print(f"[WARN] Could not generate report: {e}")

# ─────────────────────────────────────────────────────────────────────────────
#  ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(
        description="Forbidden Zone Detector v6.0  |  Live Async Pipeline\n"
                    "Run without arguments to use the GUI file-picker.",
        formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--input",        default=None)
    p.add_argument("--output",       default=None)
    p.add_argument("--model",        default="yolov8n.pt",
                   help="yolov8n / yolov8s / yolov8m / yolov8l / yolov8x")
    p.add_argument("--zone",         choices=["auto","custom","full"],
                   default="custom")
    p.add_argument("--zones",        type=int,   default=1)
    p.add_argument("--conf",         type=float, default=0.40)
    p.add_argument("--detect-scale", type=float, default=DETECT_SCALE)
    p.add_argument("--detect-every", type=int,   default=DETECT_EVERY)
    p.add_argument("--no-csv",       action="store_true")
    p.add_argument("--no-save",      action="store_true",
                   help="Do not save output video")
    args = p.parse_args()

    run(
        input_path   = args.input,
        output_path  = args.output,
        model_name   = args.model,
        zone_mode    = args.zone,
        n_zones      = args.zones,
        conf_thresh  = args.conf,
        detect_scale = args.detect_scale,
        detect_every = args.detect_every,
        csv_log      = not args.no_csv,
        save_video   = not args.no_save,
    )
